-- MySQL Script generated by MySQL Workbench
-- Seg 24 Ago 2015 12:27:35 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zf2_apiligity
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `zf2_apiligity` ;

-- -----------------------------------------------------
-- Schema zf2_apiligity
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zf2_apiligity` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `zf2_apiligity` ;

-- -----------------------------------------------------
-- Table `zf2_apiligity`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zf2_apiligity`.`clients` ;

CREATE TABLE IF NOT EXISTS `zf2_apiligity`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `document` VARCHAR(45) NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `zipcode` CHAR(9) NOT NULL,
  `city` VARCHAR(60) NOT NULL,
  `state` CHAR(2) NOT NULL,
  `responsible` VARCHAR(60) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `obs` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zf2_apiligity`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zf2_apiligity`.`products` ;

CREATE TABLE IF NOT EXISTS `zf2_apiligity`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `price` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zf2_apiligity`.`oauth_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zf2_apiligity`.`oauth_users` ;

CREATE TABLE IF NOT EXISTS `zf2_apiligity`.`oauth_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `first_name` VARCHAR(60) NOT NULL,
  `last_name` VARCHAR(60) NOT NULL,
  `role` VARCHAR(45) NOT NULL DEFAULT 'salesman',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zf2_apiligity`.`ptypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zf2_apiligity`.`ptypes` ;

CREATE TABLE IF NOT EXISTS `zf2_apiligity`.`ptypes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zf2_apiligity`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zf2_apiligity`.`orders` ;

CREATE TABLE IF NOT EXISTS `zf2_apiligity`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `ptype_id` INT NOT NULL,
  `total` DECIMAL(8,2) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_clients_idx` (`client_id` ASC),
  INDEX `fk_orders_users1_idx` (`user_id` ASC),
  INDEX `fk_orders_payment_types1_idx` (`ptype_id` ASC),
  CONSTRAINT `fk_orders_clients`
    FOREIGN KEY (`client_id`)
    REFERENCES `zf2_apiligity`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `zf2_apiligity`.`oauth_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_payment_types1`
    FOREIGN KEY (`ptype_id`)
    REFERENCES `zf2_apiligity`.`ptypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zf2_apiligity`.`oauth_access_tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zf2_apiligity`.`oauth_access_tokens` ;

CREATE TABLE IF NOT EXISTS `zf2_apiligity`.`oauth_access_tokens` (
  `access_token` VARCHAR(40) NOT NULL,
  `client_id` VARCHAR(80) NOT NULL,
  `user_id` VARCHAR(255) NULL DEFAULT NULL,
  `expires` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `scope` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`access_token`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `zf2_apiligity`.`oauth_authorization_codes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zf2_apiligity`.`oauth_authorization_codes` ;

CREATE TABLE IF NOT EXISTS `zf2_apiligity`.`oauth_authorization_codes` (
  `authorization_code` VARCHAR(40) NOT NULL,
  `client_id` VARCHAR(80) NOT NULL,
  `user_id` VARCHAR(255) NULL DEFAULT NULL,
  `redirect_uri` VARCHAR(2000) NULL DEFAULT NULL,
  `expires` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `scope` VARCHAR(2000) NULL DEFAULT NULL,
  `id_token` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`authorization_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `zf2_apiligity`.`oauth_clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zf2_apiligity`.`oauth_clients` ;

CREATE TABLE IF NOT EXISTS `zf2_apiligity`.`oauth_clients` (
  `client_id` VARCHAR(80) NOT NULL,
  `client_secret` VARCHAR(80) NOT NULL,
  `redirect_uri` VARCHAR(2000) NOT NULL,
  `grant_types` VARCHAR(80) NULL DEFAULT NULL,
  `scope` VARCHAR(2000) NULL DEFAULT NULL,
  `user_id` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`client_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `zf2_apiligity`.`oauth_jwt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zf2_apiligity`.`oauth_jwt` ;

CREATE TABLE IF NOT EXISTS `zf2_apiligity`.`oauth_jwt` (
  `client_id` VARCHAR(80) NOT NULL,
  `subject` VARCHAR(80) NULL DEFAULT NULL,
  `public_key` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`client_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `zf2_apiligity`.`oauth_refresh_tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zf2_apiligity`.`oauth_refresh_tokens` ;

CREATE TABLE IF NOT EXISTS `zf2_apiligity`.`oauth_refresh_tokens` (
  `refresh_token` VARCHAR(40) NOT NULL,
  `client_id` VARCHAR(80) NOT NULL,
  `user_id` VARCHAR(255) NULL DEFAULT NULL,
  `expires` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `scope` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`refresh_token`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `zf2_apiligity`.`oauth_scopes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zf2_apiligity`.`oauth_scopes` ;

CREATE TABLE IF NOT EXISTS `zf2_apiligity`.`oauth_scopes` (
  `type` VARCHAR(255) NOT NULL DEFAULT 'supported',
  `scope` VARCHAR(2000) NULL DEFAULT NULL,
  `client_id` VARCHAR(80) NULL DEFAULT NULL,
  `is_default` SMALLINT(6) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `zf2_apiligity`.`order_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zf2_apiligity`.`order_items` ;

CREATE TABLE IF NOT EXISTS `zf2_apiligity`.`order_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `price` DECIMAL(8,2) NOT NULL,
  `total` DECIMAL(8,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_items_orders1_idx` (`order_id` ASC),
  INDEX `fk_order_items_products1_idx` (`product_id` ASC),
  CONSTRAINT `fk_order_items_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `zf2_apiligity`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_items_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `zf2_apiligity`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zf2_apiligity`.`textx`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zf2_apiligity`.`textx` ;

CREATE TABLE IF NOT EXISTS `zf2_apiligity`.`textx` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
